name: Submit Custom Label Set
description: Submit a new or updated custom label set for the community.
title: "[Submission]: "
labels: ["custom-names", "automated-review"]

body:
  - type: markdown
    attributes:
      value: |
        ## Submission Guidelines
        Thanks for contributing to the Custom Names Community Project!
        
        **Instructions:**
        1. Fill out the fields below.
        2. Upload your text file into the "Upload File" box at the bottom.

  - type: input
    id: set_name
    attributes:
      label: Label Set Name
      description: A unique name for your set (e.g., "Funny Labels", "Serious Lore").
      placeholder: "Example: Reborn Lore Accurate Label Set"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: The version number (Integer only: 1, 2, 3, 10, 50000...). Do not use decimals (1.0).
      placeholder: "1"
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      options:
        - English
        - Arabic
        - Chinese (Simplified)
        - Chinese (Traditional)
        - French
        - German
        - Italian
        - Japanese
        - Korean
        - Portuguese
        - Russian
        - Spanish
        - Turkish
        - Other
    validations:
      required: true

  - type: input
    id: progress
    attributes:
      label: Game Progress
      description: How far into the game does this label set cover?
      placeholder: "e.g., Up to 7th Gym, Full Game, Post-game..."
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Creator's Notes
      description: Any specific comments, credits, or descriptions for the community?
    validations:
      required: false

  - type: textarea
    id: file_payload
    attributes:
      label: Upload File
      description: Upload your custom labels file  here. It should appear as a link (e.g., `[url](...)`).
      placeholder: "Upload your text file here..."
    validations:
      required: true